services:
  mongo-express:
    image: mongo-express:1
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://host.docker.internal:27017/orderdb?replicaSet=rs0&directConnection=true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
